# Generated by Django 5.1.14 on 2026-06-22 07:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("summary", models.TextField(blank=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("page", "Page"), ("file", "File")], max_length=10
                    ),
                ),
                ("body", models.TextField(blank=True)),
                ("file_url", models.URLField(blank=True)),
                ("file_name", models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
