# Generated by Django 5.1.14 on 2026-07-04 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="author",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="resource",
            name="date_made",
            field=models.DateField(default="1000-10-10"),
        ),
    ]
