# Generated by Django 5.1.14 on 2026-07-04 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0002_resource_author_resource_date_made"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="author",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
