# Generated by Django 5.1.14 on 2026-07-04 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0003_alter_resource_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="image",
            field=models.ImageField(null=True, upload_to="Resource"),
        ),
    ]
