# Generated by Django 5.1.14 on 2026-07-04 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0004_resource_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="body",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="resource",
            name="file_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="resource",
            name="file_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="resource",
            name="summary",
            field=models.TextField(blank=True, default=""),
        ),
    ]
