# Generated by Django 5.1.14 on 2026-07-11 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0005_alter_resource_body_alter_resource_file_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="image",
            field=models.ImageField(default=None, null=True, upload_to="Resource"),
        ),
    ]
