# Generated by Django 5.1.14 on 2026-07-11 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0006_alter_resource_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="image",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to="Resource"
            ),
        ),
    ]
