# Generated by Django 5.1.14 on 2026-07-11 06:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0007_alter_resource_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="date_made",
            field=models.DateField(default=datetime.date(2026, 7, 11)),
        ),
    ]
