# Generated by Django 5.1.14 on 2026-07-11 07:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0008_alter_resource_date_made"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="date_made",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
