# Generated by Django 5.1.14 on 2026-07-04 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventinstance",
            name="region",
            field=models.CharField(default="Perth", max_length=255),
        ),
    ]
