# Generated by Django 5.1.14 on 2026-07-07 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_eventinstance_region"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="cover_image",
            field=models.CharField(blank=True),
        ),
    ]
