# Generated by Django 5.1.14 on 2026-06-24 11:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("summary", models.TextField(blank=True, null=True)),
                ("body", models.TextField(blank=True, null=True)),
                ("author", models.CharField(blank=True, max_length=255, null=True)),
                ("published_at", models.DateField(blank=True, null=True)),
            ],
        ),
    ]
