# Generated by Django 5.2.16 on 2026-07-18 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="news",
            name="published_at",
            field=models.DateField(blank=True),
        ),
    ]
