# Generated by Django 5.2.16 on 2026-07-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_news_image_alter_news_published_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="image",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to="News"
            ),
        ),
    ]
